adafruit_pyportal.py
=> some more comments!

adafruit_pyportal.py
also fix ESP32 pin names, timezone key error, print out json on traverse failure
=> add text transform, reliable image converter

adafruit_pyportal.py
for use by demos like Thingiverse.
=> refactor image converter URL into function

adafruit_pyportal.py
- position images where we say they should be positioned (not ignored)
- fix word wrap helper
- allow use without a URL (no internet usage)
- nicely named touchscreen pins
- fix broken splash display (whee)
=> fix broken version and some fixes

adafruit_pyportal.py
worldtimeapi are lovely people, and we don't want to abuse their service. i've swapped it to now use adafruit io. free account needed, but we can rate-limit to avoid abuse.
=> Update to use adafruit.io for strftime service

adafruit_pyportal.py
=>  fix calls to displayio.TileGrid usage of position

examples/pyportal_simpletest.py
Works.
Not sure of a better way to do this: 
```python
board.DISPLAY.show(None)
```
Otherwise it just stays blank since we don't specify any fun things to show.
=> Add simpletest

adafruit_pyportal.py
Adding `image_url_path` to PyPortal to allow directly setting a non-json image path for API endpoints or websites without a JSON response with a provided image url (i.e: https://ddragon.leagueoflegends.com/cdn/9.6.1/img/profileicon/$Identifier.png)
=> Adding an URL-based image path kwarg to PyPortal

adafruit_pyportal.py
I needed the ability to use the wifi connection before calling adafruit_pyportal.py to do required Application authorization for Twitter's API.  Their API requires an access token from a POST request which I get so I can send adafruit_pyportal.py the GET url with the correct access token in the headers.
I'm here with you guys at pycon if that helps.
=> Added ability to pass ESP and SPI objects.

adafruit_pyportal.py
I added a method that hides the QR code after it's shown. I also added a new parameter to the show_QR method that determines whether the background should be cleared before the QR code is added.
=> Add hide_qr method & clear_background param to show_qr

adafruit_pyportal.py, docs/conf.py, examples/pyportal_simpletest.py
added function to push a data point to an adafruitio.com feed. Creates feed if it does not exist
=> Added IO_push

adafruit_pyportal.py
Changing `RESTClient` -> `IO_HTTP` to match the breaking release of Adafruit IO CircuitPython:
https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/releases/tag/2.0.0
=> Patch Adafruit IO CircuitPython to match for latest breaking release

adafruit_pyportal.py, docs/conf.py
This pull request adds support for using this library with a PyGamer/PyBadge + FeatherWing (requires `esp` and `external_spi` objects to be passed into the `init` constructor).
In addition to adding pin-compatibility, it also creates a hidden cursor object (https://github.com/adafruit/Adafruit_CircuitPython_CursorControl) if the board used with PyPortal is a PyBadge/PyGamer to substitute for the PyPortal's touchscreen.
=> Update library for PyGamer/PyBadge

adafruit_pyportal.py
attempt to fix #46 
import either touchscreen or cursor control
minimally tested -- it does import now on a PyPortal
=> choose touch screen or cursor control

adafruit_pyportal.py
Fixes https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/48 on 4.1.0 RC1. Reverts to the try/except modified by https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/pull/45
Works with no errors (incl. importerrors) when combined with  https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/pull/47
=> Fix TFT-in-use-error

adafruit_pyportal.py, docs/conf.py
This PR updates this library to use the CircuitPython_Requests module instead of ESP32SPI_Requests (req.s latest https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/pull/61)
Tested on `Adafruit CircuitPython 4.1.0-rc.1 on 2019-07-19; Adafruit PyPortal`
=> Update to CircuitPython_Requests

adafruit_pyportal.py
fixes #53 
tested on pyportal under 4.1.0 and 5.x master -- works with and with or pyportal_startup.wav  file.
=>  remove call to wait_for_frame

adafruit_pyportal.py
This code was added to allow multiple fetch() commands to work correctly when there is a mix of portrait and landscape oriented images to display on the PyPortal. An additional parameter, image_dim_json_path, was added to init() to point to the JSON section that contains the original width and height of the image. If this parameter (a width and height tuple) is not present, the fetch should work as before with no portrait mode considerations.
Here is an example of the feature being used. I commented out some of the lines so the code could run without external file dependencies. Specific landscape and portrait itemids can be uncommented  for testing, or use the randomint() function.
More info on the api used in the example is here: https://openaccess-api.clevelandart.org/
```
import time …
```
=> Update fetch() for portrait oriented images

adafruit_pyportal.py
Both __init__ and fetch access the in self._sdcard parameter to determine
if a SD card is installed. __init__ handles the mounting of the card.
fetch() alters the filename path as needed prior to calling wget(). This
new function will allow the calling of pyportal.sd_check() to determine
if a card is present and alter operations as needed.
Simple example:
if pyportal.sdcheck():
print("SD card is installed")
else:
print("SD card is NOT installed")
=> Add sd_check function to pyportal

adafruit_pyportal.py
Addressing: https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/57
Previous error with invalid Adafruit IO Account:
```
Traceback (most recent call last):
File "code.py", line 44, in <module>
File "adafruit_pyportal.py", line 629, in get_local_time
File "adafruit_pyportal.py", line 625, in get_local_time
ValueError: invalid syntax for integer with base 10 
```
New code check status code. Error text pulled from response's text:
```
Traceback (most recent call last):
File "code.py", line 25, in <module>
File "/lib/adafruit_pyportal.py", line 635, in get_local_time
File "/lib/adafruit_pyportal.py", line 624, in get_local_time
ValueError: {"error":"not found - that username does not exist"}
```
Correct operation (status code 200 OK):
```
Getting time for timezone …
```
=> Check the response status code before parsing time, raise more verbose error

adafruit_pyportal.py
The hard coded display widths and heights were wrong for the Titano and future boards that have a resolution other than 320 x 240.  Hard coded width and height replaced with board.DISPLAY.width and board.DISPLAY.height, respectively.
=> Replaced hard coded display widths and heights for Titano

adafruit_pyportal.py
Running a PyPortal Titano on CP 5.0.0-beta.4, I was getting MemoryError exceptions after 10 to 20 fetch() calls within a loop. Further research showed the memory was not low, but apparently fragmented. I added some gc.collect() calls in different functions, but that did not help. Finally, I reduced the chunk_size value from 12000 to 4096. This helped greatly, and I was able to get over 300 fetch loops (and counting) without the exception. I suggest implementing this solution until a better solution is found to address memory fragmentation with a higher higher chunk_size value.
The code used to test this issue is here:
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/PyPortal_CMA_Art_Frame
You can reduce the while loop wait to 60 seconds to help speed up the looping …
=> Reduced chunk_size to reduce memory fragmentation

adafruit_pyportal.py
Needed for integrations like AWS Lambda that require a longer wait.
=> Add timeout override

setup.py
I tried installing adafruit-circuitpython-pyportal, but it failed because it couldn't find "adafruit-circuitpython-bitmapfont," which doesn't exist.
The correct library name is "adafruit-circuitpython-bitmap-font"
=> Fixed typo "adafruit-circuitpython-bitmap-font"

setup.py
Looks like there were typos in two packages!
I've verified that it installs successfully with this second typo fix.
=> Fixed typo in "adafruit-circuitpython-display-text"

adafruit_pyportal.py
I think this resolves #17 
Tested with https://learn.adafruit.com/pyportal-github-stars-trophy/code-pyportal-with-circuitpython on PyPortal with CP Versions 4.0.0, 5.2.0, and 5.3.0.rc0
=> remove old style imports

adafruit_pyportal.py, docs/conf.py
I was testing the new json library and with this particular branch of circuitpython, but also with the latest from main, i was getting the following error while testing with the PyPortal:
Traceback (most recent call last):
File "code.py", line 35, in <module>
File "/lib/adafruit_pyportal.py", line 284, in __init__
File "/lib/adafruit_pyportal.py", line 282, in __init__
File "/lib/adafruit_pyportal.py", line 633, in play_file
AttributeError: 'module' object has no attribute 'WaveFile'
Checking the docs, it looks like WaveFile moved to audiocore.
This couple of line fixes the problem and allow the PyPortal object to be created, and example pyportal code now works ok.
=> Fixing error, WaveFile moved to audiocore

adafruit_pyportal.py, docs/conf.py
Change from adafruit_sdcard to sdcardio .
=> change from using adafruit_sdcard to sdcardio

adafruit_pyportal.py
I'm doing image conversion in my back-end. I'd like to be able to disable the use of the AIO image converter service
=> Added param to disable image converter

adafruit_pyportal.py
=> Added content-length header check

adafruit_pyportal.py
Fixes #37.
Summary of changes:
* It handles HTTP errors by outputting the error code and message and returning.
* Content type is detected as either text, json, and image and is handled better in that manner.
* This also handles the breaking changes between Requests 1.6.0 and 1.7.0 (see https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/40 for more details).
* Fake Requests was updated to be more like MatrixPortal, but should basically function the same.
Tested on CircuitPython 6 Beta 2 with latest bundle.
=> Handle HTTP errors and content type better

adafruit_pyportal.py, docs/conf.py
=> Added terminalio font support and scaling

adafruit_pyportal.py
Fixes #92. I also am raising an error for HTTP errors. The reason for this is it was returning None and later in the code giving an unrelated confusing message.
The bulk of this PR is if no Path is defined, values was an empty list and code that was written such as the weather station expected the JSON as a string to be returned. I realize loading json and using json.dumps() uses more memory, but rather than only grabbing r.text if there was no path, I didn't want to break it if the json_transform was provided which expects a dict. However, it won't load json until it actually has to so it only does it for the single edge case.
=> Raise error on HTTP Error and fix json w/ no path

adafruit_pyportal.py
When response.status_code != 200 from the REST api to TIME_SERVICE
the code raises ValueError, which is not what all the examples in
Adafruit_Learning_System_Guides handle gracefully. Instead, this
situation should be raising the RuntimeError exception.
Fixes https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/96 .
=> get_local_time is expected to raise RuntimeError when it fails

.gitignore, .pylintrc, .readthedocs.yml, CODE_OF_CONDUCT.md, LICENSE, LICENSES/CC-BY-4.0.txt, LICENSES/MIT.txt, LICENSES/Unlicense.txt, README.rst.license, adafruit_pyportal.py, docs/_static/favicon.ico.license, docs/api.rst.license, docs/conf.py, docs/examples.rst.license, docs/index.rst.license, examples/pyportal_simpletest.py, examples/pyportal_startup.wav.license, requirements.txt, setup.py.disabled
This fixes the checks failing during the pre-commit checks.
=> Add licensing info

adafruit_pyportal/__init__.py, adafruit_pyportal/network.py
I found these changes to make while working on Blinka PyPortal.
=> Add missing param docstrings, remove unused import

adafruit_pyportal/__init__.py
The Tide Viewer code was failing because it was not properly having the values extracted. Tested with Tides Viewer and Open Weather demos.
=> Added missing value extractor

docs/api.rst, docs/conf.py
Add the missing modules to api.rst
- adafruit_pyportal.graphics
- adafruit_pyportal.network
- adafruit_pyportal.peripherals
- adafruit_pyportal.wifi
=> fix api.rst to include all modules

adafruit_pyportal/__init__.py
The header parameter was not being passed to the network.fetch call.  This broke any request that required a authentication header to retrieve data  (i.e. Twitter)
I added headers=self._headers to the network.fetch call and tested with the Twitter API.
=> Added headers parameter to network.fetch call

adafruit_pyportal/wifi.py
Fixes https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/issues/24. The issue is that requests was only assigned once we called connect, but if we were already connected, requests was never assigned.
=> Assign requests if we have already connected

docs/examples.rst, docs/index.rst, examples/pyportal_internet_json_fetching.py, examples/pyportal_qrcode_generation.py
1.  Adding to examples to illustrate in a simple way: WIFI connection and JSON data fetching, QR code generation
2. adding the learning guide in the library API
3. including examples in API `examples.rst`
intends to solve #89 
Examples were tested on 
```python
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit PyPortal Titano with samd51j20
```
=> Adding examples, changing API index, examples.rst

adafruit_pyportal/__init__.py
resolves: https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/issues/57
Add a `force_content_type` argument that can be used to ignore the content_type returned from the server and treat it as the type specified.
Tested successfully with PyPortal discord learn guide project.
=> forced content type

adafruit_pyportal/peripherals.py
CircuitPython 8 builds have dropped support for `Display.auto_brightness` (https://github.com/adafruit/circuitpython/pull/6734). These changes handle the attribute no longer being available in 8.x.x, while still working on 7.x.x.
See https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2239 for a more detailed explanation.
=> handle no .auto-brightness

adafruit_pyportal/graphics.py, examples/pyportal_simpletest.py
Companion to https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/pull/95
=> replace .show with .root_group =

adafruit_pyportal/network.py
I was updating various libraries on my device while testing the cleveland art project and noticed this function had reference to old version of the secrets values, it causes an exception to be raised.
=> Update secrets usage

adafruit_pyportal/__init__.py, adafruit_pyportal/network.py, docs/conf.py, examples/pyportal_internet_json_fetching.py, examples/pyportal_simpletest.py
Minor updates to remove secrets usage and update keys:
1. Remove `secrets_data` as it will be pulled from `PortalBase`
2. Update `secrets.py` comments to `settings.toml`
3. Update AIO keys from `AIO_*` to `ADAFRUIT_AIO_*`
4. Update learn links to point to correct page for settings.toml
5. Fix `JSON_URL`
Tested both edited examples on a PyPortal running 9.2.4
=> Remove secrets and more
